server:
  port: 8762
spring:
  application:
    name: demo-cloud-erueka-server # 应用名称，也可作为服务名称

# eureka客户端配置（和Server交互） Eureka Server也是一个Client
eureka:
  instance:
    hostname: eureka8762 # 当前eureka主机名
    prefer-ip-address: false
  client:
    service-url: #配置客户端交互的Eureka Server的地址
      defaultZone: http://eureka8761:8761/eureka/
    register-with-eureka: true # 是否注册到eureka，当前自己就是server，但是并不需要注册自己 集群模式下为true
    fetch-registry: true # 查询获取注册中心的服务信息，自己就是server 集群模式下为true