server:
  port: 9001
spring:
  application:
    name: demo-service-turbine
eureka:
  client:
    service-url:
      defaultZone: http://eureka8762:8762/eureka,http://eureka8761:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
turbine:
  app-config: demo-service-autodeliver
  cluster-name-expression: "'default'"