server:
  port: 9002
eureka:
  client:
    service-url:
      # 注册到集群，就把多个eureka地址使用逗号连接即可，
      defaultZone: http://eureka8762:8762/eureka,http://eureka8761:8761/eureka
  instance:
    # 以IP形式展示 192.168.45.1而不是 LAPTOP-8QVSRNO9--主机名
    prefer-ip-address: true
    # 原来样式：IP:服务名称:端口号，例如：192.168.45.1:demo-service-resume:8080，我们可以自定义
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: demo-cloud-gateway
  cloud:
    gateway:
      routes: # 路由可以有多个
        - id: service-autodeliver-router # 我们自定义的路由 ID，保持唯一
          # uri: http://127.0.0.1:8096 # 目标服务地址 自动投递微服务。动态路由：uri配置的应该是一个服务名称
          uri: lb://demo-service-auto-resume # 目标服务地址 自动投递微服务。动态路由：uri配置的应该是一个服务名称
          predicates: # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果
            - Path=/autodeliver/**
        - id: service-resume-router
          # uri: http://127.0.0.1:8081
          uri: lb://demo-service-resume
          predicates:
            - Path=/resume/**
          filters:
            - StripPrefix=1
